In [1]:
# imporr the libraries
import numpy as np
import pandas as pd
import difflib # for comparing sequences
from sklearn.feature_extraction.text import TfidfVectorizer # for converting text to matrix of TF-IDF features
from sklearn.metrics.pairwise import cosine_similarity # to compute cosine similarity between samples in two matrices

In [2]:
# read data
song_data = pd.read_csv("./spotify_millsongdata.csv")
song_data.head()

,artist,song,link,text
0,ABBA,Ahe's My Kind Of Girl,/a/abba/ahes+my+kind+of+girl_20598417.html,"Look at her face, it's a wonderful face \nAnd..."
1,ABBA,"Andante, Andante",/a/abba/andante+andante_20002708.html,"Take it easy with me, please \nTouch me gentl..."
2,ABBA,As Good As New,/a/abba/as+good+as+new_20003033.html,I'll never know why I had to go \nWhy I had t...
3,ABBA,Bang,/a/abba/bang_20598415.html,Making somebody happy is a question of give an...
4,ABBA,Bang-A-Boomerang,/a/abba/bang+a+boomerang_20002668.html,Making somebody happy is a question of give an...

In [3]:
song_data.shape

(57650, 4)

In [4]:
# get the length of text feature
song_data["lyrics_word_count"] = (
    song_data["text"]
    .fillna("")
    .str.split()
    .str.len()
)

avg_words = song_data["lyrics_word_count"].mean()
max_words = song_data["lyrics_word_count"].max()
median_words = song_data["lyrics_word_count"].median()

print(avg_words, median_words, max_words)

219.48626192541198 196.0 827

In [5]:
song_data.isnull().sum() # not missing values

artist               0
song                 0
link                 0
text                 0
lyrics_word_count    0
dtype: int64

Their appears to be no missing values in the dataset

In [6]:
song_data.columns

Index(['artist', 'song', 'link', 'text', 'lyrics_word_count'], dtype='object')

All the features are object data types

In [7]:
song_data.dtypes

artist               object
song                 object
link                 object
text                 object
lyrics_word_count     int64
dtype: object

In [8]:
song_data.describe(include="object") # summary statistics for the categorical features

,artist,song,link,text
count,57650,57650,57650,57650
unique,643,44824,57650,57494
top,Donna Summer,Have Yourself A Merry Little Christmas,/z/zwan/heartsong_20148991.html,I just came back from a lovely trip along the ...
freq,191,35,1,6

The Artist Donna Summer is the artist with most songs in the dataset with frequency of 191

In [9]:
# Selecting features for the recommendation engine
features = ['artist', 'song', 'text'] # this are the 3 features of interest

In [ ]:
# data Cleaning
# handing missing values

In [10]:
# Creating a new combined features column
combined_features = song_data[features].apply(lambda row: ' '.join(row), axis=1)

In [11]:
# vectorizing the combined features using bounded TFIDF -
# this is important has the dataset is large over 57k.
tfidf = TfidfVectorizer(
    stop_words="english",
    max_features=25_000,   # reduced due to moderate text length
    min_df=3,
    max_df=0.85,
    ngram_range=(1, 2),
    sublinear_tf=True
)

feature_vectors = tfidf.fit_transform(combined_features)

Some settings tune for the tfidf are

* Vocabulary capped to prevent memory spikes

* Bigrams capture phrase semantics

* Sublinear TF stabilizes long lyrics

In [12]:
print(feature_vectors)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 4014310 stored elements and shape (57650, 25000)>
  Coords	Values
  (0, 59)	0.1408246904807611
  (0, 10855)	0.20529926301532886
  (0, 7415)	0.15939548480182286
  (0, 13217)	0.09587552991638981
  (0, 6113)	0.10562919257711921
  (0, 24328)	0.11187021218440683
  (0, 14609)	0.10033421944867846
  (0, 19940)	0.10401969598901274
  (0, 23659)	0.04493737060221901
  (0, 19635)	0.11540971161990923
  (0, 18924)	0.1121669533165933
  (0, 13991)	0.10310232286962355
  (0, 6560)	0.13870154862308168
  (0, 10444)	0.08297601262489347
  (0, 14238)	0.1302059178568248
  (0, 6379)	0.08627061656321465
  (0, 6649)	0.13934503595478936
  (0, 1392)	0.11168599976234889
  (0, 1860)	0.12523166728878607
  (0, 11634)	0.1687882477258094
  (0, 23198)	0.06941685199167141
  (0, 16392)	0.10691627833145695
  (0, 9601)	0.11706347864022763
  (0, 8645)	0.0661541626250361
  (0, 12787)	0.038785015072743
  :	:
  (57649, 9059)	0.08864433523286394
  (57649, 18054)	0.08430497464935774
  (57649, 19800)	0.17302117649993703
  (57649, 24381)	0.12886624464136312
  (57649, 3563)	0.14668787636328812
  (57649, 3549)	0.12419858377695056
  (57649, 24607)	0.10734801307488548
  (57649, 9499)	0.08892124962406933
  (57649, 9631)	0.06385286833778632
  (57649, 22293)	0.13431232738772053
  (57649, 14844)	0.14492442950329942
  (57649, 11822)	0.25499323879913577
  (57649, 3764)	0.28105170739272717
  (57649, 15365)	0.2904003095596513
  (57649, 12556)	0.11081407176504113
  (57649, 18655)	0.23827040855101128
  (57649, 21370)	0.13005335431150974
  (57649, 10687)	0.36081044700330656
  (57649, 18742)	0.14156349413390903
  (57649, 14225)	0.16621772964314882
  (57649, 14145)	0.15270546400332854
  (57649, 9509)	0.15662445455781626
  (57649, 11037)	0.17549245097017788
  (57649, 11796)	0.16808454561218414
  (57649, 3425)	0.17013287851267364

In [13]:
# getting the shape of the feature vectors
feature_vectors.shape

(57650, 25000)

In [14]:
# this is high dimension matrix - lets reduce the dimension using dimensionality reduction techniques 
from sklearn.decomposition import TruncatedSVD

svd = TruncatedSVD(
    n_components=200,
    random_state=42
)

feature_vectors_reduced = svd.fit_transform(feature_vectors)

The above compresses tens of thousands of sparse features into dense semantic vectors.

In [15]:
feature_vectors_reduced.shape

(57650, 200)

This reduces the feature vectors to a more manageable size while retaining most of the important information.

In [17]:
# fitting the similarity index using NearestNeighbors - using the metric cosine
from sklearn.neighbors import NearestNeighbors

nn = NearestNeighbors(
    n_neighbors=15,
    metric="cosine",
    algorithm="brute"
)

nn.fit(feature_vectors_reduced)

NearestNeighbors(algorithm='brute', metric='cosine', n_neighbors=15)

In [28]:
def recommend_from_song(song_title, k=10):
    # Find the song index
    matches = song_data[song_data["song"].str.lower() == song_title.lower()]
    
    if matches.empty:
        raise ValueError("Song not found in dataset")

    song_index = matches.index[0]

    # Find similar songs
    distances, indices = nn.kneighbors(
        feature_vectors_reduced[song_index].reshape(1, -1),
        n_neighbors=k + 1
    )

    # Exclude the input song itself
    rec_indices = indices[0][1:]

    return song_data.loc[rec_indices, ["song"]]

In [19]:
# 1 means 100% similar
# take the title of the movie from the user
list_of_all_song = song_data['song'].tolist()
list_of_all_song

["Ahe's My Kind Of Girl",
 'Andante, Andante',
 'As Good As New',
 'Bang',
 'Bang-A-Boomerang',
 'Burning My Bridges',
 'Cassandra',
 'Chiquitita',
 'Crazy World',
 'Crying Over You',
 'Dance',
 'Dancing Queen',
 'Disillusion',
 'Does Your Mother Know',
 'Dream World',
 'Dum Dum Diddle',
 'Eagle',
 'Every Good Man',
 'Fernando',
 'Fernando (In Spanish)',
 'Free As A Bumble Bee',
 'From A Twinkling Star To A Passing Angel',
 'Gimme Gimme Gimme',
 "Givin' A Little Bit More",
 'Gonna Sing You My Lovesong',
 'Hamlet III',
 'Happy Hawaii',
 'Happy New Year',
 'He Is Your Brother',
 'Head Over Heels',
 "Here We'll Stay",
 'Hey Hey Helen',
 'Hole In Your Soul',
 'Honey, Honey',
 'I Am Just A Girl',
 'I Am The City',
 'I Do, I Do, I Do, I Do, I Do',
 'I Have A Dream',
 'I Let The Music Speak',
 'I Saw It In The Mirror',
 'I Wonder (Departure)',
 'I Wonder (Departure) [Live]',
 "If It Wasn't For The Nights",
 "I'm A Marionette",
 "I've Been Waiting For You",
 'Juper Jrouper',
 'Just A Notion',
 'King Kong Song',
 'Kisses Of Fire',
 'Knowing Me Knowing You',
 'Lay All Your Love On Me',
 'Like An Angel Passing Through My Room',
 "Love Has It's Ways",
 "Love Isn't Easy",
 'Lovelight',
 'Lovers',
 'Mamma Mia',
 'Man In The Middle',
 "Me And Bobby And Bobby's Brother",
 'Me And I',
 'Merry-Go-Round',
 'Midnight Special',
 'Money Money Money',
 'Move On',
 'My Love, My Life',
 'My Mama Said',
 'Nina, Pretty Ballerina',
 'On And On And On',
 'One Man, One Woman',
 'One Of Us',
 'Our Last Summer',
 'People Need Love',
 'Pick A Bale Of Cotton',
 'Put On Your White Sombrero',
 'Reina Danzante',
 "Rikky Rock'n'Roller",
 'Ring Ring',
 'Rock Me',
 "Rock 'n Roll Band",
 'Rubber Ball Man',
 'S. O. S.',
 'Should I Laugh Or Cry',
 'Sitting In The Palmtree',
 'Slipping Through My Fingers',
 'So Long',
 'Soldiers',
 'SOS',
 'Summer Night City',
 'Suzy-Hang-Around',
 'Take A Chance',
 'Take A Chance On Me',
 'Thank You For The Music',
 "That's Me",
 'The Day Before You Came',
 'The King Has Lost His Crown',
 'The Name Of The Game',
 'The Piper',
 'The Visitors',
 'The Way Old Friends Do',
 'The Winner Takes It All',
 'Tiger',
 'Tropical Loveland',
 'Two For The Price Of One',
 'Under Attack',
 'Voulez Vous',
 'Watch Out',
 'Waterloo',
 'We Wish You A Merry Christmas',
 'What About Livingstone',
 'When All Is Said And Done',
 'When I Kissed The Teacher',
 'Why Did It Have To Be Me?',
 'You Owe Me One',
 'Always Have, Always Will',
 'Cecilia',
 "Don't Stop",
 'Edge Of Heaven',
 'Fashion Party',
 'Happy Nation',
 'Hey Darling',
 'Life Is A Flower',
 'Mercy, Mercy',
 "Never Gonna Say I'm Sorry",
 'Perfect World',
 'Who Am I',
 'Camp Granada',
 "Creepin' On The Mayor",
 'Love Stinks',
 'Mr. Bake-O',
 'Steve Polychronopolous',
 'The Adventures Of The Cow',
 'The Psychotic Legend Of Uncle Donnie',
 'Welcome My Son',
 'All I Ask',
 "Can't Let Go",
 'Crazy For You',
 'Daydreamer',
 'Hello',
 'I Miss You',
 'Melt My Heart To Stone',
 'Need You Know',
 'Now And Then',
 'Someone Like You',
 'Think That I Get Told The Court',
 "You'll Never See Me Again",
 'All Your Love',
 'Bacon Biscuit Blues',
 'Blind Man',
 'Draw The Line',
 'Eat The Rich',
 'Falling In Love',
 'Fever',
 'Get It Up',
 "I Ain't Got You",
 "I'm Ready",
 "Janie's Got A Gun",
 'Lay It Down',
 'Love In An Elevator',
 'Love Me Like A Bird Dog',
 'Love Me Two Times',
 'Luv Lies',
 'Magic Touch',
 'Make It',
 'Mama Kin',
 'Melt Down',
 'Mia',
 'Milkcow Blues',
 'Monkey On My Back',
 'Mother Popcorn',
 "Movin' Out",
 'My Fist Your Face',
 'My Girl',
 'Never Loved A Girl',
 'No More No More',
 'No Surprize',
 "Nobody's Fault",
 'Oasis In The Night',
 'On The Road Again',
 'Once Is Enough',
 'One Way Street',
 'Outta Your Head',
 "Pandora's Box",
 'Permanent Vacation',
 'Pink',
 'Prelude To Joanie',
 'Push Comes To Shove',
 'Rag Doll',
 'Rats In The Cellar',
 'Rattlesnake Shake',
 'Red House',
 'Remember',
 'Road Runner',
 'Rocket 88',
 "Rockin' Pneumonia And The Boogie Woogie Flu",
 'Round And Round',
 'Same Old Song And Dance',
 'Scream In Pain',
 'Seasons Of Wither',
 'Sedona Sunrise',
 'Shame, Shame, Shame',
 "She's On Fire",
 'Shut Up And Dance',
 'Sick As A Dog',
 'Sight For Sore Eyes',
 'Somebody',
 'Something',
 "Something's Gotta Give",
 'Spaced',
 'Spiderman Theme',
 'St. John',
 "Stop Messin' Around",
 'Sunny Side Of Love',
 'Sunshine',
 'Sweet Emotion',
 'Take It Easy',
 'Taste Of India',
 'Temperature',
 'The Farm',
 'The Grind',
 'The Hand That Feeds',
 'The Hop',
 'The Other Side',
 'The Reason A Dog',
 'Think About It',
 'This Little Light Of Mine',
 'Three Mile Smile',
 'Title Fly Away From Here',
 'Toys In The Attic',
 "Train Kept A Rollin'",
 "Trip Hoppin'",
 'Uncle Salty',
 'Under My Skin',
 'Voodoo Medicine Man',
 'Walk On Down',
 'Walk On Water',
 'A Little Bit More',
 'A Place Where We Belong',
 'After All',
 "Ain't It A Shame",
 'All By Myself',
 'All Out Of Love',
 'Alternate Ending',
 'Always',
 'American Hearts',
 'Believe In The Supernatural',
 'Believer',
 'Big Cat',
 'Black And Blue',
 'Body Glove',
 'Book Of Love',
 'Bread And Blood',
 'Bring Out The Magic',
 "Can't Fight This Feeling",
 'Come To Me',
 'Come What May',
 'Crazy Love',
 'Dancing With The Mountain',
 'Daybreak',
 'Do It Again',
 'Do What You Do',
 'Does It Matter',
 "Don't Be Afraid",
 "Don't Tell Me",
 "Don't Turn Me Away",
 "Don't Walk Away",
 'Empty Pages',
 'End Of The Line',
 'Even The Nights Are Better',
 'Every Woman In The World',
 'Evidence Of Love',
 'Evil Woman',
 'Faith',
 'Hard To Forget Her',
 'Heart Of The Rose',
 'Here I Am',
 'Hope Springs Eternal',
 "I Can't Believe My Eyes",
 "I Can't Get Excited",
 "I Can't Let Go",
 'I Come Alive (Date With An Angel)',
 "I Don't Believe You",
 "I Don't Want To Lose You",
 'I Just Like The Feeling',
 'I Know You Better Than You Think',
 'I Remember Love',
 'I Wanna Hold You Tonight',
 'I Want To Give It All',
 'I Want You',
 'If You Love Me',
 "I'll Be Thinking Of You",
 "I'll Find You",
 "I'll Never Get Enough Of You",
 "I'm Alive",
 "It's Automatic",
 "It's Never Too Late",
 "It's Not Easy",
 "It's Not Too Late",
 "I've Got Your Love",
 'Just Another Woman',
 'Just As I Am',
 'Just Between The Lines',
 'Late Again',
 'Love Comes To Me',
 'Love Conquers Time',
 'Love Is All',
 'Love Is The Arrow',
 'Make It Right',
 'Making Love Out Of Nothing At All',
 'Miracles',
 'More Than Natural',
 'Mother Said',
 'My Best Friend',
 'My Hearts With You',
 'Never Fade Away',
 'News From Nowhere',
 "Nothing's Gonna Change My Love For You",
 'Now And Forever',
 'O Come All Ye Faithful',
 'Old Habits Die Hard',
 'One Step Closer',
 'Only One Forever',
 'Peaches And Cream',
 'Ready For You',
 'Secret Agent',
 'Shadow Of The Sun',
 'She Never Heard Me Call',
 'Sleigh Ride',
 'Someone',
 'Someone Who Believes In You',
 'Speaking Of Love',
 'Spirit Of Love',
 'Stars In Your Eyes',
 'Stop The Tears',
 'Strangers In Love',
 'Strong Strong Wind',
 'Stronger Than The Night',
 'Sunset',
 'Swear To Your Heart',
 'Sweet Dreams',
 'Taking The Chance',
 'The First Noel',
 'Tonite',
 'Too Sentimental',
 'Total Eclipse Of The Heart',
 'We The People',
 'Winter Wonderland',
 'Fool Til The End',
 'Friend Of Mine',
 'Huwag Mong Iwan Ang Puso',
 'I See You Lord',
 'If',
 'If We Try',
 'Ikaw Ang Aking Mahal',
 'Ikaw Na Ang Bahala: Panalangin',
 'Laughter In The Rain',
 'Open Arms',
 'Pakisabi Na Lang',
 'Put A Little Love In Your Heart',
 'Sa Huli Ang Sikat',
 'Sa Ugoy Ng Duyan',
 'Sorry',
 'Calling All Angels',
 "Can't Keep A Good Man Down",
 'Carolina Mountain Dew',
 'Christmas In Dixie',
 'Christmas In Your Arms',
 'Christmas Is Love',
 'Christmas Shoes',
 'Church In The Wildwood',
 'Clear Across America Tonight',
 'Clear Water Blues',
 'Close Enough To Perfect',
 'Country Side Of Life',
 "Dancin', Shaggin' On The Boulevard",
 'Dixie Boy',
 'Dixie Fire',
 'Dixieland Delight',
 'Down By The Riverside',
 'Down Home',
 'Down On Longboat Key',
 'Down On The River',
 'Down This Road',
 "Fallin' Again",
 'Fantasy',
 'Feels So Right',
 'Fire On Fire',
 'Fireworks',
 "Five O'clock 500",
 'Food On The Table',
 "Forever's As Far As I'll Go",
 'Getting Over You',
 'Give Me One More Shot',
 'God Must Have Spent A Little More Time On You',
 'Gonna Have A Party',
 'Goodbye',
 'Green River',
 'Gulf Of Mexico',
 "Hangin' Round The Mistletoe",
 "Hanging Up My Travelin' Shoes",
 'Happy Birthday Jesus',
 'Happy Holidays',
 'Hats Off',
 'Heartbreak Express',
 'Here We Are',
 'Hey Baby',
 'High Cotton',
 'His Eye Is On The Sparrow',
 'Hollywood',
 "I Ain't Got No Business Doin'",
 'I Love You Enough To Let You Go',
 'I Write A Little',
 'If I Could Just See You Now',
 'If I Had You',
 "If It Ain't Dixie",
 "If You're Gonna Play In Texas",
 "I'm In A Hurry",
 "I'm In A Hurry (And Don't Know Why)",
 "I'm In That Kind Of Mood",
 "I'm In The Mood",
 "I'm Not That Way Anymore",
 "I'm Still Dreamin'",
 "I'm Stoned",
 'Jukebox In My Mind',
 'Katy Brought My Guitar Back Today',
 'Lady Down On Love',
 'Little Things',
 'Lonesome Valley',
 'Love In The First Degree',
 "Lovin' Man",
 'Once Upon A Lifetime',
 'Pass It On Down',
 'Precious Memories',
 'Reckless',
 'She Can',
 'Small Stuff',
 'Tar Top',
 'Tennessee River',
 'The Boy',
 'The Woman He Loves',
 'Then Again',
 'All Our Yesterdays',
 "Can't Take It With You",
 'Days Are Numbers',
 "Don't Answer Me",
 "Don't Let The Moment Pass",
 'Eye In The Sky',
 'Fall Free',
 'Games People Play',
 'Gemini',
 "I'd Rather Be A Man",
 'May Be A Price To Pay',
 'Mr. Time',
 'So Far Away',
 'Somebody Out There',
 'Take The Money And Run',
 'The Cask Of Amontillado',
 'The Eagle Will Rise Again',
 'The Fall Of The House Of Usher - I Prelude',
 'The Raven',
 'The Real World',
 'The Ring',
 'The Same Old Sun',
 '(The System Of) Doctor Tarr And Professor Fether',
 'The Tell-Tale Heart',
 'The Turn Of A Friendly Card',
 'The Turn Of A Friendly Card (Part 1)',
 'The Turn Of A Friendly Card (Part One)',
 'The Voice',
 'There But For The Grace Of God',
 'Time',
 'We Play The Game',
 'Make Me A Channel Of Your Peace',
 'Walking In The Air',
 'Apple Bush',
 'Ballad Of Dwight Fry',
 'Be My Lover',
 'Be With You Awhile',
 'Between High School And The Old School',
 'Blue Turk',
 'Changing, Arranging',
 "Clones (We're All)",
 "Crawlin'",
 'Damned If You Do',
 'Dead Babies',
 'Department Of Youth',
 'Desperado',
 "Devil's Food",
 "Didn't We Meet",
 'Die For You',
 'Dirty Diamonds',
 'Disgraceland',
 "Enough's Enough",
 'For Britain Only',
 'Gail',
 'Give It Up',
 'Give The Radio Back',
 "Goin' To The River",
 'Headlines',
 "He's Back",
 'I Better Be Good',
 'I Just Wanna Be God',
 'I Like Girls',
 'I Love America',
 'I Miss You',
 'I Never Wrote Those Songs',
 "I'm Alive",
 "It's Much Too Late",
 'Killer',
 'Lace And Whiskey',
 "Love's A Loaded Gun",
 'Lullaby',
 'Millie And Billie',
 'Nuclear Infected',
 'Poison',
 'Refrigerator Heaven',
 'Remarkably Insincere',
 'Angry Chair',
 'Dam That River',
 'Fat Girls',
 'God Smack',
 'Grind',
 "Heaven N' Hell",
 'Love Song',
 'No Excuses',
 'Over The Edge',
 'Private Hell',
 'Put You Down',
 'Queen Of The Rodeo',
 'Real Thing',
 'Rooster',
 'Rotten Apple',
 'Sealed With A Kiss',
 'Shame In You',
 'Sickman',
 'Stay',
 'Sunshine',
 'Swing On This',
 'Whatcha Gonna Do',
 'But You Know I Love You',
 'Dimming Of The Day',
 'Dreaming My Dreams With You',
 'Faraway Land',
 'Foolish Heart',
 'Fortune Teller',
 'Gentle River',
 'Gravity',
 'Here Comes Goodbye',
 'I Can Let Go Now',
 'If I Give My Heart',
 'In The Palm Of Your Hand',
 "It Doesn't Matter",
 "It's Over",
 'Jesus Help Me To Stand',
 'Jubilee',
 'Killing The Blues',
 'Lay Down Beside Me',
 'Lay My Burden Down',
 'Lie Awake',
 "Lord Don't Forsake Me",
 'Lucky One',
 'Maybe',
 'On The Borderline',
 'Paper Airplane',
 'Pastures Of Plenty',
 'Shield Of Faith',
 'Shimmy Down The Chimney (Fill Up My Stocking)',
 'That Kind Of Love',
 "What'll I Do",
 'When God Dips His Pen Of Love In My Heart',
 'Who Can Blame You',
 'Will You Be Leaving',
 'Your Long Journey',
 "Ain't No Good To Cry",
 'Bad Rain',
 'Been Gone Too Long',
 'Brothers Of The Road',
 'Demons',
 'Every Hungry Woman',
 'Good Time Feelin',
 "Leavin'",
 'Let Me Ride',
 'Mean Old World',
 'Mean Woman Blues',
 'Midnight Blues',
 'Morning Dew',
 'Mystery Woman',
 'Nancy',
 'Need Your Love So Bad',
 'Never Knew How Much',
 'No Money Down',
 'Old Friend',
 'Sail Away',
 "Sailin' 'cross The Devil's Sea",
 'Shine It On',
 'Straight From The Heart',
 'The Heat Is On',
 'The Weight',
 'Things You Used To Do',
 'Two Rights',
 'Woman Across The River',
 "You Don't Love Me",
 'Afternoons In Utopia',
 "Ain't It Strange",
 'Apollo',
 'Ariana',
 'Ascension Day',
 'Carol Masters',
 'Five Years',
 'For The Sake Of Love',
 'Forever Young',
 'Giants',
 'Girl From Pachacamac',
 'Golden Feeling',
 'Guardian Angel',
 'Headlines',
 'Heart Of The Flower',
 'Heaven Or Hell',
 'Here By Your Side',
 'Iron John',
 'Ivory Tower',
 'Middle Of The Riddle',
 'Monkey In The Moon',
 'Moon Boy',
 'New Horizons',
 'Roll Away The Stone',
 'Sensations',
 'Shadows She Said',
 'Ship Of Fools',
 'Sister Sun',
 'Some People',
 'Soul Messiah',
 'Sounds Like A Melody',
 'Summer In Berlin',
 'The Opium Den',
 'The Other Side Of You',
 'Wishful Thinking',
 'A Horse With No Name',
 'Bell Tree',
 "Can't Fall Asleep To A Lullaby",
 "Can't You See",
 'Cast The Spirit',
 'Catch That Train',
 'Chasing The Rainbow',
 'Children',
 'Christmas In California',
 'Cinderella',
 'Clarice',
 'Close To The Wind',
 'Company',
 'Desperate Love',
 "Don't Cry Baby",
 "Don't Let It Get You Down",
 'Down To The Water',
 'Even The Score',
 "Foolin'",
 'Garden Of Peace',
 'Glad To See You',
 'God Of The Sun',
 'Golden',
 'Goodbye',
 'Goodbye Highway',
 'Have Yourself A Merry Little Christmas',
 'Here',
 'High In The City',
 'Hope',
 'In The Country',
 'In The Sea',
 'International',
 'Jet Boy Blue',
 'Let It Snow',
 'Letter',
 'Lonely People',
 "Love's Worn Out Again",
 'Mad Dog',
 'Moon Song',
 'My Dear',
 'My Kinda Woman',
 'Never Be Lonely',
 'Never Found The Time',
 'No Fortune',
 'Old Virginia',
 'Oloololo',
 'One Morning',
 'Playing God',
 'Ports-Of-Call',
 'Riverside',
 'Saturn Nights',
 'Seasons',
 "She's A Liar",
 "She's Gonna Let You Down",
 'Simple Life',
 'Sleigh Ride',
 'Slow Down',
 'Sometimes Lovers',
 'Submarine Ladies',
 'Take It Easy',
 'The Border',
 'These Brown Eyes',
 "Today's The Day",
 'Town And Country',
 'Valentine',
 'A Christmas To Remember',
 'Abide With Me',
 'After The Fire',
 'Ageless Medley',
 'All I Ever Have To Be',
 'Baby Baby',
 'Beautiful Music',
 "Christmas Can't Be Very Far Away",
 'Christmas Lullaby',
 'Do You Remember The Time',
 'Every Heartbeat',
 'Father',
 'Fill Me With Your Love',
 'I Will Remember You',
 'If You Have To Go Away',
 "It's Not A Song",
 'Jehovah',
 "Life's Gonna Change",
 'Mountain Top',
 'Nobody Home',
 'Not Giving Up',
 'Nothing Is Beyond You',
 'O Little Town',
 'O Love That Will Not Let Me Go',
 'O Master, Let Me Walk With Thee',
 'O Sacred Head',
 "Old Man's Rubble",
 'Out In The Open',
 "Santa's Reindeer Ride",
 'Say Once More',
 'So Glad',
 'Sweet Will Of God',
 'The Power',
 'The Things We Do For Love',
 'Power Of Love',
 'Sogno',
 'Someone Like You',
 'Voglio Restare Cosi',
 'When A Child Is Born',
 'A Fool Never Learns',
 'Baby Doll',
 'Christmas Needs Love To Be Christmas',
 'Days Of Wine And Roses',
 'Falling In Love With Love',
 'I Will Wait For You',
 'If I Could Only Go Back Again',
 "I'm So Lonesome I Could Cry",
 "It's A Most Unusual Day",
 'Love Song Of Kalua',
 'Love Story',
 'May Each Day',
 'More Today Than Yesterday',
 'My Sweet Lord',
 'One Day Of Your Life',
 'Quiet Night Of Quiet Stars',
 "Say It Isn't So",
 'Show Me',
 'So Rare',
 'Still Under The Weather',
 'The Bilbao Song',
 'Walk Hand In Hand',
 'Where Or When',
 'Winter Wonderland',
 'Words By Lorenz Hart And Music By Richard Rodgers',
 "Wouldn't It Be Loverly",
 'Wrong For Each Other',
 "You Don't Want My Love",
 'Back Together',
 'Carring The Banner',
 'Heartbeat',
 'We Got Annie',
 "We'D Like To Thank You",
 'Baby I',
 'Break Free',
 'Direct Contact',
 'Higher',
 'Honeymoon Avenue',
 'Just A Little Bit Of Your Heart',
 'Not Just On Christmas',
 'Pink Champagne',
 'Right There',
 'Why Try',
 'A Smile In Your Heart',
 'Both Inlove',
 "I Don't Love You Anymore (duet With Lea Salonga)",
 'Minamahal Pala Kita',
 'All Over The World',
 'Anytime',
 'Buffalo Skinners',
 'Children Of Abraham',
 'Coming Into Los Angeles',
 'Cowboy Song',
 'Dead Or Alive',
 'Drowning Man',
 'Eli',
 'Evangelina',
 'Every Hand In The Land',
 'Gates Of Eden',
 "Hobo's Lullaby",
 'I Ride On Old Pain',
 "Jacob's Ladder",
 'Jamaica Farewell',
 'John Looked Down',
 'Last Night I Had The Strangest Dream',
 'Last To Leave',
 'Last Train',
 'Lay Down Little Doggies',
 'Living Like A Legend',
 'Lord Grenville',
 'Lovesick Blues',
 'Manzanillo Bay',
 'Massachusetts',
 'Miss The Mississippi And You',
 'Mystic Journey',
 'Now And Then',
 'Oklahoma Hills',
 "Patriot's Dream",
 "Percy's Song",
 'Power Of Love',
 'Prologue',
 "Ridin' Down The Canyon",
 'Sailing Down This Golden River',
 'Shenandoah',
 'Somebody Turned On The Light',
 'Someday',
 'Telephone',
 'The Gal I Left Behind',
 'The Motorcycle Song',
 'The Motorcycle Song (In Album Arlo)',
 'The Pause Of Mr. Claus',
 'The Streets Of Laredo',
 'This Land Is Your Land',
 'This Troubled Mind Of Mine',
 'Ukulele Lady',
 'Uncle Jeff',
 'Under Cover Of Night',
 'Unemployment Line',
 'Utah Carroll',
 'Victor Jara',
 'Wheel Of Fortune',
 'When A Soldier Makes It Home',
 'When The Cactus Is In Bloom',
 'When The Ship Comes In',
 'You And Me',
 'A Man Has Needs',
 'Baby Poo',
 'Big Fat Road Manager',
 'Billy Themepark Shark',
 'Bottle Of Booze',
 'Boy Band',
 'Carrot Juice Is Murder',
 'Celine Dion',
 'Christmas Blues',
 'Christmas Hangover',
 'Christmas In Ignace',
 'Christmas Sucks',
 'Christmas Turkey Blues',
 'Dog Named Bob',
 "Don't Go Into Politics",
 'Drink With Me',
 'Going Hunting',
 'Great To Be A Nerd',
 'Heimlich Maneuver',
 'History Is Made By Stupid People',
 'I Am Cow!!!!',
 'I Pulled My Groin',
 "Jesus' Brother Bob",
 'Kill The Dog Next Door',
 'Login To You',
 'Malcolm',
 'Me Like Hockey!',
 'Mounted Animal Nature Trail',
 'My Voice Is Changing',
 'New Car Smell',
 "Oh God, I'm Santa Claus",
 'Particle Board',
 'Proud T O Be A Banker',
 'Proud To Be Canadian',
 'Really Scary',
 "Steel Drivin' Man",
 'The Ballad Of Dan',
 'The Golf Song',
 'The Happy Happy Birthday Song',
 'The Monkey Song',
 'The Mountie Song',
 'The War Of 1812',
 'Tv Weather Guy',
 '17',
 'All The Small Things (Blink 182 Cover)',
 'Anything But Ordinary',
 'Bad Reputation',
 'Complicated',
 'Contagious',
 'Despise You',
 'Destiny',
 'Eternity',
 'Everyday Again',
 'Fall Into You',
 'Fall To Pieces',
 'Falling Down',
 'Falling Fast',
 'Falling Into History',
 'Feeling Sorry For Myself',
 'Fly',
 'Foolish (Leave Me Alone)',
 'Forgotten',
 "He Wasn't",
 'Hello Kitty',
 "Here's To Never Growing Up",
 "Here's Your Letter (Toronto Concert)",
 'Hold',
 'How Does It Feel',
 'I Always Get What I Want',
 'I Love You',
 'I Will Be',
 "I Won't Be Home For Christmas",
 "I'm Feeling This Dude",
 'In The End',
 'Kiss Me',
 "Knockin On Hevean's Door",
 'Let Go',
 'Losing Grip',
 'Make Up',
 'Naked',
 'Not Enough',
 'Not The Only One',
 'One Of Those Girls',
 'Remember When',
 'Rock N Roll',
 "Sippin' On Sunshine",
 'Sk8er Boi',
 'Slipped Away',
 'Smells Like Teen Spirit (Live)',
 'Smile',
 'So Damn Hard',
 'Sometimes',
 'Stay (Be The One)',
 'Stop Standing There',
 'Take It',
 'Take Me Away',
 'Take Me Away (Original)',
 'The Best Damn Thing',
 'The Hockey Song',
 'The Other Guy',
 'The Punk Show',
 'The Scientist',
 'The Spongebob Squarepants Theme',
 "Tomorrow You Didn't",
 'Too Much To Ask',
 'Touch The Sky',
 'Touchdown Boy',
 'Trust Me',
 'Unsolved Mysteries',
 'Unwanted',
 'Waggy',
 'Waste Of Time',
 'What The Hell',
 'Why',
 "You Ain't Seen Nothin' Yet",
 'You Never Satisfy Me',

In [ ]:
# Recommends top 10 songs similar to "Siberia"
print(recommend_from_song("Siberia", k=10))

                      song
6872   I Can't Go For That
29710         Baby It's Me
17109           Then I Did
41436     Someone Like You
27711             Memories
37726     Time In A Bottle
35478         Did You Know
29951  Dreams Do Come True
45677     I'd Come For You
19922      It's My Delight

In [ ]:
# checking wether thier is duplicate song titles
# how will I know 
duplicate_songs = song_data[song_data.duplicated(subset=['song'], keep=False)]
duplicate_songs_sorted = duplicate_songs.sort_values(by='song')

In [21]:
duplicate_songs_sorted

,artist,song,link,text,lyrics_word_count
50299,Ray Charles,'Deed I Do,/r/ray+charles/deed+i+do_20618784.html,"\nDo I want you? \nOh my do I \nHoney, ind...",88
30995,Ella Fitzgerald,'Deed I Do,/e/ella+fitzgerald/deed+i+do_20813472.html,"Do I want you? \nOh my do I \nHoney, indeed ...",88
10249,Kelly Clarkson,(Love Will) Turn Back The Hands Of Time,/k/kelly+clarkson/love+will+turn+back+the+hand...,[Kelly] \nNo more midnight rides with you \n...,267
7197,Grease,(Love Will) Turn Back The Hands Of Time,/g/grease/love+will+turn+back+the+hands+of+tim...,[Stephanie] \nNo more midnight rides with you...,266
4722,Electric Light Orchestra,10538 Overture,/e/electric+light+orchestra/10538+overture_200...,"Did you see your friend, crying from his eyes ...",98
...,...,...,...,...,...
4829,Ellie Goulding,Your Song,/e/ellie+goulding/your+song_20895401.html,It's a little bit funny \nThis feeling inside...,207
5203,Engelbert Humperdinck,Yours,/e/engelbert+humperdinck/yours_20504122.html,Yours till the stars have no glory \nYours ti...,106
55005,Vera Lynn,Yours,/v/vera+lynn/yours_20354375.html,Yours 'til the stars lose their glory \nYours...,99
4762,Electric Light Orchestra,Zing Went The Strings Of My Heart,/e/electric+light+orchestra/zing+went+the+stri...,"Dear, when you smile at me \nI hear a melody ...",105
39123,Judy Garland,Zing Went The Strings Of My Heart,/j/judy+garland/zing+went+the+strings+of+my+he...,"Never could carry a tune, never knew where to ...",236